development:
  sessions:
    default:
      database: nice_trip_development
      hosts:
        - localhost:27017
      options:
  options:
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      database: nice_trip_production
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0